# fly.toml app configuration file generated for grizzly on 2023-07-14T14:43:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grizzly"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "./server/Dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
